/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmmRouteImport } from './routes/smm'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SmmServiceIdRouteImport } from './routes/smm.$serviceId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSmmServicesRouteImport } from './routes/admin.smm-services'
import { Route as AdminSmmProvidersRouteImport } from './routes/admin.smm-providers'
import { Route as AdminSmmPollLogRouteImport } from './routes/admin.smm-poll-log'
import { Route as AdminSmmOrdersRouteImport } from './routes/admin.smm-orders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AccountIdRouteImport } from './routes/account.$id'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated.wallet'
import { Route as AuthenticatedSmmOrdersRouteImport } from './routes/_authenticated.smm-orders'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated.purchases'
import { Route as AuthenticatedFundRouteImport } from './routes/_authenticated.fund'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiWalletInitializeFundingRouteImport } from './routes/api/wallet/initialize-funding'
import { Route as ApiSmmPlaceOrderRouteImport } from './routes/api/smm/place-order'
import { Route as ApiSmmAdminTestRouteImport } from './routes/api/smm/admin/test'
import { Route as ApiSmmAdminSyncRouteImport } from './routes/api/smm/admin/sync'
import { Route as ApiSmmAdminCronRouteImport } from './routes/api/smm/admin/cron'
import { Route as ApiPublicWebhooksKorapayRouteImport } from './routes/api/public/webhooks/korapay'
import { Route as ApiPublicSmmPollRouteImport } from './routes/api/public/smm/poll'
import { Route as ApiPublicProvidersSyncRouteImport } from './routes/api/public/providers/sync'

const SmmRoute = SmmRouteImport.update({
  id: '/smm',
  path: '/smm',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SmmServiceIdRoute = SmmServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => SmmRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmmServicesRoute = AdminSmmServicesRouteImport.update({
  id: '/smm-services',
  path: '/smm-services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmmProvidersRoute = AdminSmmProvidersRouteImport.update({
  id: '/smm-providers',
  path: '/smm-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmmPollLogRoute = AdminSmmPollLogRouteImport.update({
  id: '/smm-poll-log',
  path: '/smm-poll-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmmOrdersRoute = AdminSmmOrdersRouteImport.update({
  id: '/smm-orders',
  path: '/smm-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIdRoute = AccountIdRouteImport.update({
  id: '/account/$id',
  path: '/account/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSmmOrdersRoute = AuthenticatedSmmOrdersRouteImport.update({
  id: '/smm-orders',
  path: '/smm-orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFundRoute = AuthenticatedFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiWalletInitializeFundingRoute =
  ApiWalletInitializeFundingRouteImport.update({
    id: '/api/wallet/initialize-funding',
    path: '/api/wallet/initialize-funding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSmmPlaceOrderRoute = ApiSmmPlaceOrderRouteImport.update({
  id: '/api/smm/place-order',
  path: '/api/smm/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmmAdminTestRoute = ApiSmmAdminTestRouteImport.update({
  id: '/api/smm/admin/test',
  path: '/api/smm/admin/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmmAdminSyncRoute = ApiSmmAdminSyncRouteImport.update({
  id: '/api/smm/admin/sync',
  path: '/api/smm/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmmAdminCronRoute = ApiSmmAdminCronRouteImport.update({
  id: '/api/smm/admin/cron',
  path: '/api/smm/admin/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKorapayRoute =
  ApiPublicWebhooksKorapayRouteImport.update({
    id: '/api/public/webhooks/korapay',
    path: '/api/public/webhooks/korapay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmmPollRoute = ApiPublicSmmPollRouteImport.update({
  id: '/api/public/smm/poll',
  path: '/api/public/smm/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvidersSyncRoute = ApiPublicProvidersSyncRouteImport.update({
  id: '/api/public/providers/sync',
  path: '/api/public/providers/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/smm': typeof SmmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fund': typeof AuthenticatedFundRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smm-orders': typeof AuthenticatedSmmOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smm-orders': typeof AdminSmmOrdersRoute
  '/admin/smm-poll-log': typeof AdminSmmPollLogRoute
  '/admin/smm-providers': typeof AdminSmmProvidersRoute
  '/admin/smm-services': typeof AdminSmmServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/smm/$serviceId': typeof SmmServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/smm/place-order': typeof ApiSmmPlaceOrderRoute
  '/api/wallet/initialize-funding': typeof ApiWalletInitializeFundingRoute
  '/api/public/providers/sync': typeof ApiPublicProvidersSyncRoute
  '/api/public/smm/poll': typeof ApiPublicSmmPollRoute
  '/api/public/webhooks/korapay': typeof ApiPublicWebhooksKorapayRoute
  '/api/smm/admin/cron': typeof ApiSmmAdminCronRoute
  '/api/smm/admin/sync': typeof ApiSmmAdminSyncRoute
  '/api/smm/admin/test': typeof ApiSmmAdminTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/smm': typeof SmmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fund': typeof AuthenticatedFundRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smm-orders': typeof AuthenticatedSmmOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smm-orders': typeof AdminSmmOrdersRoute
  '/admin/smm-poll-log': typeof AdminSmmPollLogRoute
  '/admin/smm-providers': typeof AdminSmmProvidersRoute
  '/admin/smm-services': typeof AdminSmmServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/smm/$serviceId': typeof SmmServiceIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/smm/place-order': typeof ApiSmmPlaceOrderRoute
  '/api/wallet/initialize-funding': typeof ApiWalletInitializeFundingRoute
  '/api/public/providers/sync': typeof ApiPublicProvidersSyncRoute
  '/api/public/smm/poll': typeof ApiPublicSmmPollRoute
  '/api/public/webhooks/korapay': typeof ApiPublicWebhooksKorapayRoute
  '/api/smm/admin/cron': typeof ApiSmmAdminCronRoute
  '/api/smm/admin/sync': typeof ApiSmmAdminSyncRoute
  '/api/smm/admin/test': typeof ApiSmmAdminTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/smm': typeof SmmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fund': typeof AuthenticatedFundRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/smm-orders': typeof AuthenticatedSmmOrdersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/smm-orders': typeof AdminSmmOrdersRoute
  '/admin/smm-poll-log': typeof AdminSmmPollLogRoute
  '/admin/smm-providers': typeof AdminSmmProvidersRoute
  '/admin/smm-services': typeof AdminSmmServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/category/$slug': typeof CategorySlugRoute
  '/smm/$serviceId': typeof SmmServiceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/smm/place-order': typeof ApiSmmPlaceOrderRoute
  '/api/wallet/initialize-funding': typeof ApiWalletInitializeFundingRoute
  '/api/public/providers/sync': typeof ApiPublicProvidersSyncRoute
  '/api/public/smm/poll': typeof ApiPublicSmmPollRoute
  '/api/public/webhooks/korapay': typeof ApiPublicWebhooksKorapayRoute
  '/api/smm/admin/cron': typeof ApiSmmAdminCronRoute
  '/api/smm/admin/sync': typeof ApiSmmAdminSyncRoute
  '/api/smm/admin/test': typeof ApiSmmAdminTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/smm'
    | '/dashboard'
    | '/fund'
    | '/purchases'
    | '/settings'
    | '/smm-orders'
    | '/wallet'
    | '/account/$id'
    | '/admin/categories'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/smm-orders'
    | '/admin/smm-poll-log'
    | '/admin/smm-providers'
    | '/admin/smm-services'
    | '/admin/users'
    | '/admin/wallet'
    | '/category/$slug'
    | '/smm/$serviceId'
    | '/admin/'
    | '/api/smm/place-order'
    | '/api/wallet/initialize-funding'
    | '/api/public/providers/sync'
    | '/api/public/smm/poll'
    | '/api/public/webhooks/korapay'
    | '/api/smm/admin/cron'
    | '/api/smm/admin/sync'
    | '/api/smm/admin/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/smm'
    | '/dashboard'
    | '/fund'
    | '/purchases'
    | '/settings'
    | '/smm-orders'
    | '/wallet'
    | '/account/$id'
    | '/admin/categories'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/smm-orders'
    | '/admin/smm-poll-log'
    | '/admin/smm-providers'
    | '/admin/smm-services'
    | '/admin/users'
    | '/admin/wallet'
    | '/category/$slug'
    | '/smm/$serviceId'
    | '/admin'
    | '/api/smm/place-order'
    | '/api/wallet/initialize-funding'
    | '/api/public/providers/sync'
    | '/api/public/smm/poll'
    | '/api/public/webhooks/korapay'
    | '/api/smm/admin/cron'
    | '/api/smm/admin/sync'
    | '/api/smm/admin/test'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/smm'
    | '/_authenticated/dashboard'
    | '/_authenticated/fund'
    | '/_authenticated/purchases'
    | '/_authenticated/settings'
    | '/_authenticated/smm-orders'
    | '/_authenticated/wallet'
    | '/account/$id'
    | '/admin/categories'
    | '/admin/diagnostics'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/providers'
    | '/admin/settings'
    | '/admin/smm-orders'
    | '/admin/smm-poll-log'
    | '/admin/smm-providers'
    | '/admin/smm-services'
    | '/admin/users'
    | '/admin/wallet'
    | '/category/$slug'
    | '/smm/$serviceId'
    | '/admin/'
    | '/api/smm/place-order'
    | '/api/wallet/initialize-funding'
    | '/api/public/providers/sync'
    | '/api/public/smm/poll'
    | '/api/public/webhooks/korapay'
    | '/api/smm/admin/cron'
    | '/api/smm/admin/sync'
    | '/api/smm/admin/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  SmmRoute: typeof SmmRouteWithChildren
  AccountIdRoute: typeof AccountIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiSmmPlaceOrderRoute: typeof ApiSmmPlaceOrderRoute
  ApiWalletInitializeFundingRoute: typeof ApiWalletInitializeFundingRoute
  ApiPublicProvidersSyncRoute: typeof ApiPublicProvidersSyncRoute
  ApiPublicSmmPollRoute: typeof ApiPublicSmmPollRoute
  ApiPublicWebhooksKorapayRoute: typeof ApiPublicWebhooksKorapayRoute
  ApiSmmAdminCronRoute: typeof ApiSmmAdminCronRoute
  ApiSmmAdminSyncRoute: typeof ApiSmmAdminSyncRoute
  ApiSmmAdminTestRoute: typeof ApiSmmAdminTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smm': {
      id: '/smm'
      path: '/smm'
      fullPath: '/smm'
      preLoaderRoute: typeof SmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/smm/$serviceId': {
      id: '/smm/$serviceId'
      path: '/$serviceId'
      fullPath: '/smm/$serviceId'
      preLoaderRoute: typeof SmmServiceIdRouteImport
      parentRoute: typeof SmmRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smm-services': {
      id: '/admin/smm-services'
      path: '/smm-services'
      fullPath: '/admin/smm-services'
      preLoaderRoute: typeof AdminSmmServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smm-providers': {
      id: '/admin/smm-providers'
      path: '/smm-providers'
      fullPath: '/admin/smm-providers'
      preLoaderRoute: typeof AdminSmmProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smm-poll-log': {
      id: '/admin/smm-poll-log'
      path: '/smm-poll-log'
      fullPath: '/admin/smm-poll-log'
      preLoaderRoute: typeof AdminSmmPollLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smm-orders': {
      id: '/admin/smm-orders'
      path: '/smm-orders'
      fullPath: '/admin/smm-orders'
      preLoaderRoute: typeof AdminSmmOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/$id': {
      id: '/account/$id'
      path: '/account/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/smm-orders': {
      id: '/_authenticated/smm-orders'
      path: '/smm-orders'
      fullPath: '/smm-orders'
      preLoaderRoute: typeof AuthenticatedSmmOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fund': {
      id: '/_authenticated/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AuthenticatedFundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/wallet/initialize-funding': {
      id: '/api/wallet/initialize-funding'
      path: '/api/wallet/initialize-funding'
      fullPath: '/api/wallet/initialize-funding'
      preLoaderRoute: typeof ApiWalletInitializeFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smm/place-order': {
      id: '/api/smm/place-order'
      path: '/api/smm/place-order'
      fullPath: '/api/smm/place-order'
      preLoaderRoute: typeof ApiSmmPlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smm/admin/test': {
      id: '/api/smm/admin/test'
      path: '/api/smm/admin/test'
      fullPath: '/api/smm/admin/test'
      preLoaderRoute: typeof ApiSmmAdminTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smm/admin/sync': {
      id: '/api/smm/admin/sync'
      path: '/api/smm/admin/sync'
      fullPath: '/api/smm/admin/sync'
      preLoaderRoute: typeof ApiSmmAdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smm/admin/cron': {
      id: '/api/smm/admin/cron'
      path: '/api/smm/admin/cron'
      fullPath: '/api/smm/admin/cron'
      preLoaderRoute: typeof ApiSmmAdminCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/korapay': {
      id: '/api/public/webhooks/korapay'
      path: '/api/public/webhooks/korapay'
      fullPath: '/api/public/webhooks/korapay'
      preLoaderRoute: typeof ApiPublicWebhooksKorapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/smm/poll': {
      id: '/api/public/smm/poll'
      path: '/api/public/smm/poll'
      fullPath: '/api/public/smm/poll'
      preLoaderRoute: typeof ApiPublicSmmPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/providers/sync': {
      id: '/api/public/providers/sync'
      path: '/api/public/providers/sync'
      fullPath: '/api/public/providers/sync'
      preLoaderRoute: typeof ApiPublicProvidersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFundRoute: typeof AuthenticatedFundRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmmOrdersRoute: typeof AuthenticatedSmmOrdersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFundRoute: AuthenticatedFundRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmmOrdersRoute: AuthenticatedSmmOrdersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmmOrdersRoute: typeof AdminSmmOrdersRoute
  AdminSmmPollLogRoute: typeof AdminSmmPollLogRoute
  AdminSmmProvidersRoute: typeof AdminSmmProvidersRoute
  AdminSmmServicesRoute: typeof AdminSmmServicesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmmOrdersRoute: AdminSmmOrdersRoute,
  AdminSmmPollLogRoute: AdminSmmPollLogRoute,
  AdminSmmProvidersRoute: AdminSmmProvidersRoute,
  AdminSmmServicesRoute: AdminSmmServicesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SmmRouteChildren {
  SmmServiceIdRoute: typeof SmmServiceIdRoute
}

const SmmRouteChildren: SmmRouteChildren = {
  SmmServiceIdRoute: SmmServiceIdRoute,
}

const SmmRouteWithChildren = SmmRoute._addFileChildren(SmmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  SmmRoute: SmmRouteWithChildren,
  AccountIdRoute: AccountIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiSmmPlaceOrderRoute: ApiSmmPlaceOrderRoute,
  ApiWalletInitializeFundingRoute: ApiWalletInitializeFundingRoute,
  ApiPublicProvidersSyncRoute: ApiPublicProvidersSyncRoute,
  ApiPublicSmmPollRoute: ApiPublicSmmPollRoute,
  ApiPublicWebhooksKorapayRoute: ApiPublicWebhooksKorapayRoute,
  ApiSmmAdminCronRoute: ApiSmmAdminCronRoute,
  ApiSmmAdminSyncRoute: ApiSmmAdminSyncRoute,
  ApiSmmAdminTestRoute: ApiSmmAdminTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
